Aquidemia/config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/gyms'

  resources :gyms do
  member do
    post :vote_up
  end

  member do
    post :vote_down
  end
  
  member do
    post :add_favorite
  end
  
  member do
    post :remove_favorite
  end
  end
  # index page / root url
  root 'pages#home', as: 'home'
  
  get 'pages/home'
  
  get 'pages/search'

  get 'pages/favorites'

  get 'pages/about'
  
  get 'pages/gyms'
  
  get 'auth/:provider/callback', to: 'sessions#create'
  
  get 'logout', to: 'sessions#destroy'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Aquidemia/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Aquidemia/app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

Aquidemia/app/models/gym.rb
class Gym < ApplicationRecord
    acts_as_voteable
    acts_as_followable
end

Aquidemia/app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  acts_as_follower
  def self.update_or_create(auth)
    user = User.find_by(uid: auth[:uid]) || User.new
    user.attributes = {
      provider: auth[:provider],
      uid: auth[:uid],
      email: auth[:info][:email],
      first_name: auth[:info][:first_name],
      last_name: auth[:info][:last_name],
      token: auth[:credentials][:token],
      refresh_token: auth[:credentials][:refresh_token],
      oauth_expires_at: auth[:credentials][:expires_at]
    }
    user.save!
    user
  end
end

Aquidemia/app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, lambda { order("created_at DESC") }

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable if ActiveRecord::VERSION::MAJOR < 4


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

Aquidemia/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:id]) if session[:id] rescue nil
  end
end

Aquidemia/app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, only: [:show, :edit, :update, :destroy]
  
  def add_favorite
    begin
      @gym = Gym.find(params[:id])
      current_user.follow(@gym)
      render :show
    end
  end
  
  def remove_favorite
    begin
      @gym = Gym.find(params[:id])
      current_user.stop_following(@gym)
      render :show
    end
  end
     
  def vote_up
    begin
      @gym = Gym.find(params[:id])
      if current_user.voted_for?(@gym)
        current_user.unvote_for(@gym)
        render :show
      else
        current_user.vote_exclusively_for(@gym)   
        render :show
      end
    end
  end

  def vote_down
    begin
      @gym = Gym.find(params[:id])
      if current_user.voted_against?(@gym)
        current_user.unvote_for(@gym)
        render :show
      else
        current_user.vote_exclusively_against(@gym)   
        render :show
      end
    end
  end
  # GET /gyms
  # GET /gyms.json
  def index
    @gyms = Gym.all
  end

  # GET /gyms/1
  # GET /gyms/1.json
  def show
    @gym = Gym.find(params[:id])
  end

  # GET /gyms/new
  def new
    @gym = Gym.new
  end

  # GET /gyms/1/edit
  def edit
  end

  # POST /gyms
  # POST /gyms.json
  def create
    @gym = Gym.new(gym_params)

    respond_to do |format|
      if @gym.save
        format.html { redirect_to @gym, notice: 'Gym was successfully created.' }
        format.json { render :show, status: :created, location: @gym }
      else
        format.html { render :new }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gyms/1
  # PATCH/PUT /gyms/1.json
  def update
    respond_to do |format|
      if @gym.update(gym_params)
        format.html { redirect_to @gym, notice: 'Gym was successfully updated.' }
        format.json { render :show, status: :ok, location: @gym }
      else
        format.html { render :edit }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gyms/1
  # DELETE /gyms/1.json
  def destroy
    @gym.destroy
    respond_to do |format|
      format.html { redirect_to gyms_url, notice: 'Gym was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gym
      @gym = Gym.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gym_params
      params.require(:gym).permit(:number, :rpa, :microregion, :cnes, :name, :adress, :bairro, :phone, :latitude, :longitude, :hour, :rating)
    end
end

Aquidemia/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def gyms
    @gyms = Gym.all
  end
  
  def search
    @gyms = Gym.all
  end
  
end

Aquidemia/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.update_or_create(request.env["omniauth.auth"])
    session[:id] = user.id
    redirect_to home_path
  end

  def destroy
    session.clear
    redirect_to home_path
  end
end

Aquidemia/app/helpers/application_helper.rb
module ApplicationHelper
end

Aquidemia/app/helpers/gyms_helper.rb
module GymsHelper
end

Aquidemia/app/helpers/pages_helper.rb
module PagesHelper
end

Aquidemia/app/helpers/sessions_helper.rb
module SessionsHelper
end

Aquidemia/app/views/gyms/_form.html.erb
<%= form_with(model: gym, local: true) do |form| %>
  <% if gym.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gym.errors.count, "error") %> prohibited this gym from being saved:</h2>

      <ul>
      <% gym.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :gym_number %>
  </div>

  <div class="field">
    <%= form.label :rpa %>
    <%= form.number_field :rpa, id: :gym_rpa %>
  </div>

  <div class="field">
    <%= form.label :microregion %>
    <%= form.text_field :microregion, id: :gym_microregion %>
  </div>

  <div class="field">
    <%= form.label :cnes %>
    <%= form.number_field :cnes, id: :gym_cnes %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :gym_name %>
  </div>

  <div class="field">
    <%= form.label :adress %>
    <%= form.text_field :adress, id: :gym_adress %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :gym_bairro %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :gym_phone %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :gym_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :gym_longitude %>
  </div>

  <div class="field">
    <%= form.label :hour %>
    <%= form.text_field :hour, id: :gym_hour %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating, id: :gym_rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Aquidemia/app/views/gyms/edit.html.erb
<h1>Editing Gym</h1>

<%= render 'form', gym: @gym %>

<%= link_to 'Show', @gym %> |
<%= link_to 'Back', gyms_path %>

Aquidemia/app/views/gyms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gyms</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Rpa</th>
      <th>Microregion</th>
      <th>Cnes</th>
      <th>Name</th>
      <th>Adress</th>
      <th>Bairro</th>
      <th>Phone</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Hour</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gyms.each do |gym| %>
      <tr>
        <td><%= gym.number %></td>
        <td><%= gym.rpa %></td>
        <td><%= gym.microregion %></td>
        <td><%= gym.cnes %></td>
        <td><%= gym.name %></td>
        <td><%= gym.adress %></td>
        <td><%= gym.bairro %></td>
        <td><%= gym.phone %></td>
        <td><%= gym.latitude %></td>
        <td><%= gym.longitude %></td>
        <td><%= gym.hour %></td>
        <td><%= gym.rating %></td>
        <td><%= link_to 'Show', gym %></td>
        <td><%= link_to 'Edit', edit_gym_path(gym) %></td>
        <td><%= link_to 'Destroy', gym, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gym', new_gym_path %>

Aquidemia/app/views/gyms/new.html.erb
<h1>New Gym</h1>

<%= render 'form', gym: @gym %>

<%= link_to 'Back', gyms_path %>

Aquidemia/app/views/gyms/show.html.erb
<!DOCTYPE html>
<html lang='pt-br'>
  <style>
  .button {
    background-color: #f44336;
    border: none;
    border-radius: 8px;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
  }
  .button:hover {
    background-color: #4CAF50; /* Green */
    color: white;
}
  </style>
<body>  
<div class="container">
    <div style="text-align:justify" class="jumbotron">  
      <p id="notice"><%= notice %></p>
       <p>
        <strong>Nome:</strong>
        <%= @gym.name %>
      </p>
      
      <p>
        <strong>Microrregião:</strong>
        <%= @gym.microregion %>
      </p>
      
      <p>
        <strong>Cnes:</strong>
        <%= @gym.cnes %>
      </p>
      
      <p>
        <strong>Endereço:</strong>
        <%= @gym.adress %>
      </p>
      
      <p>
        <strong>Bairro:</strong>
        <%= @gym.bairro %>
      </p>
      
      <p>
        <strong>Telefone:</strong>
        <%= @gym.phone %>
      </p>
      
      <p>
        <strong>Horário:</strong>
        <%= @gym.hour %>
      </p>
      
      <p>
        <strong>Nota:</strong>
        <table style="width:30%">      
            <tr>
              <th>Likes</th>
              <th>Dislikes</th>
              <th>Favoritos</th>
            </tr>
              <td><%= @gym.votes_for %></td>
              <td><%= @gym.votes_against %></td>
              <td><%= @gym.followers_count %></td>
            </tr>
          </table>
      </p>
      
      <% if current_user  %>
        <% if current_user.voted_for?(@gym) %>
          <p>Você avaliou essa academia positivamente</p>
        <% end %>
        <% if current_user.voted_against?(@gym) %>
          <p>Você avaliou essa academia negativamente</p>
        <% end %>
        <p>
        Avaliação:
        <div style="text-align:center" class="fundo">
          <%= link_to vote_up_gym_path(@gym), :method => :post, class: "button_like" do %>
            <i class="icon-like fa fa-thumbs-up"></i>
          <% end %>
          |
          <%= link_to vote_down_gym_path(@gym), :method => :post, class: "button_dislike" do %>
            <i class="icon-dislike fa fa-thumbs-down"></i>
          <% end %>
          |
          <% if current_user.following?(@gym) %>
            <%= link_to('Remova dos favoritos', remove_favorite_gym_path(@gym), :method => :post) %>
          <% else %>
            <%= link_to('Adicione aos favoritos', add_favorite_gym_path(@gym), :method => :post) %>
          <% end %>
          </div>
        </p>
      <% else %>
        <a href="/auth/google" class="button"><font color="black">Faça login para avaliar academias</font></a>
      <% end %>
      
      <p style="text-align:center">
      <%= link_to "Academias", pages_gyms_path, class: "button2 button2-sucess" %>  
      </p>
</div>

<p><div>Icons made by <a href="https://www.flaticon.com/authors/dave-gandy" title="Dave Gandy">Dave Gandy</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div></p>
</body>

Aquidemia/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Aquidemia" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>


    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= image_tag("navbar-logo.png", :alt => "navbar-logo feed", :class => "navbar-logo") %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', home_path=%></li>
            <li><%= link_to 'Buscar', pages_search_path=%></li>
            <li><%= link_to 'Academias', pages_gyms_path=%></li>
            <li><%= link_to 'Favoritos', pages_favorites_path=%></li>
            <li><%= link_to 'Sobre', pages_about_path=%></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
          </div><!--/.well -->
        </div><!--/span-->

    

    </div> <!-- /container -->

  </body>
</html>

Aquidemia/app/views/pages/about.html.erb
<!DOCTYPE html>
<div style="text-align:justify" class="container">
    <div class="jumbotron">
        <h4>Projeto da disciplina IF977 - Engenharia de Software, do curso de Sistemas de Informação - CIN (UFPE)</h4>
       
        <br></br>
        
        <b>Equipe:</b>
            <p>Thomás Torreão de Brito Bastos (Gerente de Projeto e Desenvolvedor back-end)<br />
            Antônio Rodrigues da Mata Neto (Desenvolvedor back-end)<br />
            Gabriel Mac’Hamilton Renaux Alves (Desenvolvedor front-end)<br />
            Tiago Oliveira de Souza (Desenvolvedor back-end)</p>
        
        <b>Descrição:</b>
        
        <p>O projeto tem como objetivo facilitar o acesso das pessoas às academias da
        cidade, disponibilizando a academia mais próxima do usuário, os horários das
        aulas, telefone para contato, entre outras informações pertinentes ao
        estabelecimento. A aplicação utiliza dados abertos de Academias do Recife que
        podem ser encontrados neste <a href="http://dados.recife.pe.gov.br/
        dataset/academias-da-cidade">link</a>.</p>
        
        <b>Justificativa do projeto:</b>
        
        <p>Atualmente as pessoas precisam da prática de exercícios físicos para a
        manutenção da saúde, porém, a falta de informações muitas vezes cria um 
        empecilho para tais práticas. É aí que entra o Aquidemia! O aplicativo 
        será um facilitador para que as pessoas obtenham informações e se motivem
        a ir cuidar de sua saúde, usufruindo dos benefícios do serviço das Academias
        da Cidade.</p>
        

        
        <b>Mais informações:</b>
        
        <p>O código do projeto está disponível no 
        <a href=https://github.com/gmachamilton/Aquidemia-Projeto-IF977>GitHub</a>.</p>
        
        <b>Contato:</b>
        <al>
        <li><a href=https://github.com/ardmn9>Antônio</a></li>
        <li><a href=https://github.com/gmachamilton>Gabriel</a></li>
        <li><a href=https://github.com/thomastbb>Thomas</a></li>
        <li><a href=https://github.com/Tos96>Tiago</a></li>
        </al>
</div>

Aquidemia/app/views/pages/favorites.html.erb
<!DOCTYPE html>
<html lang='pt-br'>
  <style>
  .button {
    background-color: #f44336;
    border: none;
    border-radius: 8px;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
  }
  .button:hover {
    background-color: #4CAF50; /* Green */
    color: white;
}
  </style>
<% if current_user  %>
  <div class="container">
        <div class="jumbotron">
          <p class="lead">
          <h2>Favoritos</h2>
          </p>
        </div>
<table style="width:100%">
  <tr>
    <th>Academia</th>
    <th>Informações</th>
  </tr>
  <% current_user.all_following.each do |gym| %>
    <tr>
      <td><%= gym.name%></td>
      <td><%= link_to 'Detalhes', gym %></td>
    </tr>
  <% end %>
</table>

<% else %>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h3>Login necessário!</h3></br>
        <a href="/auth/google" class="button"><font color="black">Login com Google</font></a>
        <p class="lead"></p>
      </div>
<% end %>

Aquidemia/app/views/pages/gyms.html.erb
<div class="container">
      <div class="jumbotron">
        <p class="lead">
        <h2>Academias</h2>
        </p>
      </div>

<table style="width:100%">
  <tr>
    <th>Academia</th>
    <th>Horários</th>
    <th>Avaliação</th>
    <th>Informações</th>
  </tr>
  <% @gyms.each do |gym| %>
    <tr>
      <td><%= gym.name%></td>
      <td><%= gym.hour%></td>
      <td><%= gym.plusminus%></td>
      <td><%= link_to 'Detalhes', gym %></td>
    </tr>
  <% end %>
</table>
</html>

Aquidemia/app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang='pt-br'>
  <style>
  .button {
    background-color: #f44336;
    border: none;
    border-radius: 8px;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
  }
  .button:hover {
    background-color: #4CAF50; /* Green */
    color: white;
}
  .button2 {
    background-color: #4CAF50;
    border: none;
    border-radius: 8px;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
  }
  .button2:hover {
    background-color: #f44336; /* Green */
    color: white;
}

  </style>
  
  <head>
    <meta charset="utf-8">
    <meta name="google-signin-client_id" content="266046558432-sfe2c3p2a2m1172qbnopdb8am904389q.apps.googleusercontent.com">
    
  </head>
  
  <body>
    <div class="container">
      <div class="jumbotron">
        <%= image_tag("home-logo.png", :alt => "home-logo feed", :class => "home-logo") %>
        <h2 style="text-align:center" class="display-4">Descubra as Academias da Cidade próximas de você!</h2>
        <hr class="my-4">
        <p></p>
        <p style="text-align:center" class="lead">
         <% if current_user  %>
           <h3>Bem vindo, <%= "#{current_user.first_name} #{current_user.last_name}" %></h3>
           <%= link_to "Sair", logout_path, class: "button2 button2-sucess" %>
         <% else %>
           <a href="/auth/google" class="button"><font color="black">Login com Google</font></a>
         <% end %>
        </p>
      </div>
      
      <p id='msg'></p>
      <script>
      </script>
    </div>
  </body>
</html>

Aquidemia/app/views/pages/hour.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div class="container">
      <div class="jumbotron">
        <p class="lead">
        <h2>Horários das aulas</h2>
        </p>
      </div>
<table style="width:60%">
  <tr>
    <th>Academias</th>
    <th>Horários</th>
  </tr>
  <% @gyms.each do |gym| %>
    <tr>
      <td><%= gym.name%></td>    
      <td><%= gym.hour%></td>
    </tr>
  <% end %>
</table>
</html>

Aquidemia/app/views/pages/search.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      #map {
        width: 100%;
        height: 600px;
      }
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
        color: #000;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <p class="lead">
        <t style="color:#fff; float:justify" >Digite seu endereço, selecione seu modo de viagem e começe a navegar.</t>
        </p>
        <hr class="my-4">
        <font color="#fff">Seu endereço: </font>
        <input id="address" type="textbox" value="Recife, Marco Zero">
        <input id="submit" type="button" value="Posicionar">
        <br></br>
        <font color="#fff">Modo de viagem: </font>
        <select id="mode">
          <option value="DRIVING">Dirigindo</option>
          <option value="WALKING">Andando</option>
          <option value="BICYCLING">Bicicleta</option>
          <option value="TRANSIT">Trânsito</option>
        </select>
    </div>
    <div id="map"></div>
    <script>
      var lastMarker;
      function initMap() {
        directionsDisplay = new google.maps.DirectionsRenderer({
          suppressMarkers: true
        });
        directionsService = new google.maps.DirectionsService();
        var map = new google.maps.Map(document.getElementById('map'), {
          center: new google.maps.LatLng(-8.0621058, -34.8710205),
          zoom: 14,
        });
        directionsDisplay.setMap(map);
        var geocoder = new google.maps.Geocoder();
        document.getElementById('submit').addEventListener('click', function() {
          geocodeAddress(geocoder, map);
        });   
        start = new google.maps.LatLng(-8.0621058, -34.8710205);
        lastMarker = new google.maps.Marker({
          title: "Posição padrão",
          position: start,
          icon: pinSymbol("#FF1"),
        });
        lastMarker.setMap(map)
        "<% @gyms.each do |gym| %>"
          var contentString = '<div id="content">'+
            '<div id="siteNotice">'+
            '<h4 id="firstHeading" class="firstHeading"><%= gym.name %></h4>'+
            '<div id="bodyContent">'+
            '<t>Clique em detalhes para mais informações: </t>'+
            '<%= link_to 'Detalhes', gym, :target => "_blank"%>'+
            '</div>'+
            '<t>Se você já inseriu seu endereço descubra a rota: </t>'+
            '<button type="button" class="custom_button" onclick="return calcRoute();">Mostrar rota</button>'+
            '</div>';
          var marker = new google.maps.Marker({
            title: "<%= gym.name %>",
            optimized: false,
            position: new google.maps.LatLng("<%= gym.latitude %>", "<%= gym.longitude %>")
          });
          attachListener(marker);
          function attachListener(marker) {
            var infowindow = new google.maps.InfoWindow({
              content: contentString
            });            
            marker.addListener('click', function() {
              infowindow.open(marker.get('map'), marker);
              latmarker = marker.getPosition().lat();
              lngmarker = marker.getPosition().lng();
              end = new google.maps.LatLng(latmarker, lngmarker);
            });
          }
          marker.setMap(map);
        "<% end %>"
      }
      function geocodeAddress(geocoder, resultsMap) {
        lastMarker.setMap(null);
        var address = document.getElementById('address').value;
        geocoder.geocode({'address': address}, function(results, status) {
          if (status === 'OK') {
            start = results[0].geometry.location
            resultsMap.setCenter(results[0].geometry.location);
            lastMarker = new google.maps.Marker({
              title: 'Sua localização',
              map: resultsMap,
              optimized: false,
              position: results[0].geometry.location,
              icon: pinSymbol("#FF1"),
            });
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
      } 
      function pinSymbol(color) {
        return {
          path: 'M 0,0 C -2,-20 -10,-22 -10,-30 A 10,10 0 1,1 10,-30 C 10,-22 2,-20 0,0 z M -2,-30 a 2,2 0 1,1 4,0 2,2 0 1,1 -4,0',
          fillColor: color,
          fillOpacity: 1,
          strokeColor: '#000',
          strokeWeight: 2,
          scale: 1.5,
        };
      }  
      function calcRoute() {
        var selectedMode = document.getElementById('mode').value;
        var request = {
          origin: start,
          destination: end,
          travelMode: google.maps.TravelMode[selectedMode]
        };
        directionsService.route(request, function(result, status) {
        if (status == 'OK') {
          directionsDisplay.setDirections(result);
        }
        });
       }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAEFL4I3GmmiTxOjSvAKZo2r_E1Pk6weDU&callback=initMap">
    </script>
  </body>
</html>